//https://www.ryanhowerter.net/colors.php

export const fullSolidColor = [
  { colorDesc: "White", color: "F4F4F4", colorNum: "1" },
  { colorDesc: "Grey", color: "8A928D", colorNum: "2" },
  { colorDesc: "Light Yellow", color: "FFD67F", colorNum: "3" },
  { colorDesc: "Brick Red", color: "F2705E", colorNum: "4" },
  { colorDesc: "Brick Yellow", color: "CCB98D", colorNum: "5" },
  { colorDesc: "Light Green", color: "ADD9A8", colorNum: "6" },
  { colorDesc: "Orange", color: "FF8500", colorNum: "7" },
  { colorDesc: "Cobalt Blue", color: "8C00FF", colorNum: "8" },
  { colorDesc: "Light Reddish Violet", color: "F6A9BB", colorNum: "9" },
  { colorDesc: "Pastel Blue", color: "ABD9FF", colorNum: "11" },
  { colorDesc: "Light Orange Brown", color: "D86D2C", colorNum: "12" },
  { colorDesc: "Red Orange", color: "FF8014", colorNum: "13" },
  { colorDesc: "Pastel Green", color: "78FC78", colorNum: "14" },
  { colorDesc: "Lemon", color: "FFF230", colorNum: "15" },
  { colorDesc: "Pink", color: "FF879C", colorNum: "16" },
  { colorDesc: "Rose", color: "FF9494", colorNum: "17" },
  { colorDesc: "Nougat", color: "BB805A", colorNum: "18" },
  { colorDesc: "Light Brown", color: "CF8A47", colorNum: "19" },
  { colorDesc: "Bright Red", color: "B40000", colorNum: "21" },
  { colorDesc: "Medium Reddish Violet", color: "D05098", colorNum: "22" },
  { colorDesc: "Bright Blue", color: "1E5AA8", colorNum: "23" },
  { colorDesc: "Bright Yellow", color: "FAC80A", colorNum: "24" },
  { colorDesc: "Earth Orange", color: "543324", colorNum: "25" },
  { colorDesc: "Black", color: "000000", colorNum: "26" },
  { colorDesc: "Dark Grey", color: "545955", colorNum: "27" },
  { colorDesc: "Dark Green", color: "00852B", colorNum: "28" },
  { colorDesc: "Medium Green", color: "7FC475", colorNum: "29" },
  { colorDesc: "Light Yellowish Orange", color: "FDC383", colorNum: "36" },
  { colorDesc: "Bright Green", color: "58AB41", colorNum: "37" },
  { colorDesc: "Dark Orange", color: "91501C", colorNum: "38" },
  { colorDesc: "Light Bluish Violet", color: "AFBED6", colorNum: "39" },
  { colorDesc: "Light Blue", color: "97CBD9", colorNum: "45" },
  { colorDesc: "Light Red", color: "EDC4B5", colorNum: "100" },
  { colorDesc: "Medium Red", color: "DA8678", colorNum: "101" },
  { colorDesc: "Medium Blue", color: "7396C8", colorNum: "102" },
  { colorDesc: "Light Grey", color: "BCB4A5", colorNum: "103" },
  { colorDesc: "Bright Violet", color: "671FA1", colorNum: "104" },
  { colorDesc: "Bright Yellowish Orange", color: "F58624", colorNum: "105" },
  { colorDesc: "Bright Orange", color: "D67923", colorNum: "106" },
  { colorDesc: "Bright Bluish Green", color: "069D9F", colorNum: "107" },
  { colorDesc: "Earth Yellow", color: "56472F", colorNum: "108" },
  { colorDesc: "Bright Bluish Violet", color: "26469A", colorNum: "110" },
  { colorDesc: "Medium Bluish Violet", color: "4861AC", colorNum: "112" },
  { colorDesc: "Medium Yellowish Green", color: "B7D425", colorNum: "115" },
  { colorDesc: "Medium Bluish Green", color: "00AAA4", colorNum: "116" },
  { colorDesc: "Light Bluish Green", color: "9CD6CC", colorNum: "118" },
  { colorDesc: "Bright Yellowish Green", color: "A5CA18", colorNum: "119" },
  { colorDesc: "Light Yellowish Green", color: "DEEA92", colorNum: "120" },
  { colorDesc: "Medium Yellowish Orange", color: "F89A39", colorNum: "121" },
  { colorDesc: "Bright Reddish Orange", color: "EE5434", colorNum: "123" },
  { colorDesc: "Bright Reddish Violet", color: "901F76", colorNum: "124" },
  { colorDesc: "Light Orange", color: "F9A777", colorNum: "125" },
  { colorDesc: "Dark Nougat", color: "AD6140", colorNum: "128" },
  { colorDesc: "Neon Orange", color: "EF5828", colorNum: "133" },
  { colorDesc: "Neon Green", color: "CDDD34", colorNum: "134" },
  { colorDesc: "Sand Blue", color: "70819A", colorNum: "135" },
  { colorDesc: "Sand Violet", color: "75657D", colorNum: "136" },
  { colorDesc: "Medium Orange", color: "F48147", colorNum: "137" },
  { colorDesc: "Sand Yellow", color: "897D62", colorNum: "138" },
  { colorDesc: "Earth Blue", color: "19325A", colorNum: "140" },
  { colorDesc: "Earth Green", color: "00451A", colorNum: "141" },
  { colorDesc: "Sand Green", color: "708E7C", colorNum: "151" },
  { colorDesc: "Sand Red", color: "88605E", colorNum: "153" },
  { colorDesc: "(New) Dark Red", color: "720012", colorNum: "154" },
  { colorDesc: "Curry", color: "DD982E", colorNum: "180" },
  { colorDesc: "Tiny Blue", color: "009ECE", colorNum: "188" },
  { colorDesc: "Fire Yellow", color: "FFCF0B", colorNum: "190" },
  { colorDesc: "Flame Yellowish Orange", color: "FCAC00", colorNum: "191" },
  { colorDesc: "Reddish Brown", color: "5F3109", colorNum: "192" },
  { colorDesc: "Flame Reddish Orange", color: "EC441D", colorNum: "193" },
  { colorDesc: "Medium Stone Grey", color: "969696", colorNum: "194" },
  { colorDesc: "Royal Blue", color: "1C58A7", colorNum: "195" },
  { colorDesc: "Dark Royal Blue", color: "0E3E9A", colorNum: "196" },
  { colorDesc: "Bright Lilac", color: "312B87", colorNum: "197" },
  { colorDesc: "Bright Reddish Lilac", color: "8A12A8", colorNum: "198" },
  { colorDesc: "Dark Stone Grey", color: "646464", colorNum: "199" },
  { colorDesc: "Light Stone Grey", color: "C8C8C8", colorNum: "208" },
  { colorDesc: "Dark Curry", color: "A47624", colorNum: "209" },
  { colorDesc: "Faded Green", color: "468A5F", colorNum: "210" },
  { colorDesc: "Turquoise", color: "3FB6A9", colorNum: "211" },
  { colorDesc: "Light Royal Blue", color: "9DC3F7", colorNum: "212" },
  { colorDesc: "Medium Royal Blue", color: "476FB6", colorNum: "213" },
  { colorDesc: "Rust", color: "872B17", colorNum: "216" },
  { colorDesc: "Brown", color: "7B5D41", colorNum: "217" },
  { colorDesc: "Reddish Lilac", color: "8E5597", colorNum: "218" },
  { colorDesc: "Lilac", color: "564E9D", colorNum: "219" },
  { colorDesc: "Light Lilac", color: "9195CA", colorNum: "220" },
  { colorDesc: "Bright Purple", color: "C8509B", colorNum: "221" },
  { colorDesc: "Light Purple", color: "FF9ECD", colorNum: "222" },
  { colorDesc: "Light Pink", color: "F17880", colorNum: "223" },
  { colorDesc: "Light Brick Yellow", color: "F3C988", colorNum: "224" },
  { colorDesc: "Warm Yellowish Orange", color: "FAA964", colorNum: "225" },
  { colorDesc: "Cool Yellow", color: "FFEC6C", colorNum: "226" },
  { colorDesc: "Dove Blue", color: "77C9D8", colorNum: "232" },
  { colorDesc: "Light Faded Green", color: "60BA76", colorNum: "233" },
  { colorDesc: "Medium Lilac", color: "441A91", colorNum: "268" },
  { colorDesc: "Tiny-Medium Blue", color: "3E95B6", colorNum: "269" },
  { colorDesc: "Light Nougat", color: "E1BEA1", colorNum: "283" },
  { colorDesc: "Dark Brown", color: "352100", colorNum: "308" },
  { colorDesc: "Medium Nougat", color: "AA7D55", colorNum: "312" },
  { colorDesc: "Dark Azur", color: "469BC3", colorNum: "321" },
  { colorDesc: "Medium Azur", color: "68C3E2", colorNum: "322" },
  { colorDesc: "Aqua", color: "D3F2EA", colorNum: "323" },
  { colorDesc: "Medium Lavender", color: "A06EB9", colorNum: "324" },
  { colorDesc: "Lavender", color: "CDA4DE", colorNum: "325" },
  { colorDesc: "Spring Yellowish Green", color: "E2F99A", colorNum: "326" },
  { colorDesc: "Olive Green", color: "8B844F", colorNum: "330" },
  { colorDesc: "Vibrant Coral", color: "FD5F84", colorNum: "353" },
  { colorDesc: "Vibrant Yellow", color: "F5F500", colorNum: "368" },
  { colorDesc: "Medium Brown", color: "755945", colorNum: "370" },
  { colorDesc: "Warm Tan", color: "CCA373", colorNum: "371" },
];

